/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/site'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalTokenRouteImport } from './routes/portal.$token'
import { Route as AppModulosFuturosRouteImport } from './routes/_app/modulos-futuros'
import { Route as AppMeuSiteRouteImport } from './routes/_app/meu-site'
import { Route as AppIndicacoesRouteImport } from './routes/_app/indicacoes'
import { Route as AppFinanceiroRouteImport } from './routes/_app/financeiro'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppBibliotecaRouteImport } from './routes/_app/biblioteca'
import { Route as AppAgendaRouteImport } from './routes/_app/agenda'
import { Route as AppPortalIndexRouteImport } from './routes/_app/portal.index'
import { Route as AppOrdensIndexRouteImport } from './routes/_app/ordens.index'
import { Route as AppOrcamentosIndexRouteImport } from './routes/_app/orcamentos.index'
import { Route as AppClientesIndexRouteImport } from './routes/_app/clientes.index'
import { Route as AppOrdensIdRouteImport } from './routes/_app/ordens.$id'
import { Route as AppOrcamentosNovoRouteImport } from './routes/_app/orcamentos.novo'
import { Route as AppOrcamentosIdRouteImport } from './routes/_app/orcamentos.$id'
import { Route as AppClientesIdRouteImport } from './routes/_app/clientes.$id'

const SiteRoute = SiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppModulosFuturosRoute = AppModulosFuturosRouteImport.update({
  id: '/modulos-futuros',
  path: '/modulos-futuros',
  getParentRoute: () => AppRoute,
} as any)
const AppMeuSiteRoute = AppMeuSiteRouteImport.update({
  id: '/meu-site',
  path: '/meu-site',
  getParentRoute: () => AppRoute,
} as any)
const AppIndicacoesRoute = AppIndicacoesRouteImport.update({
  id: '/indicacoes',
  path: '/indicacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppBibliotecaRoute = AppBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalIndexRoute = AppPortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdensIndexRoute = AppOrdensIndexRouteImport.update({
  id: '/ordens/',
  path: '/ordens/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentosIndexRoute = AppOrcamentosIndexRouteImport.update({
  id: '/orcamentos/',
  path: '/orcamentos/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIndexRoute = AppClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdensIdRoute = AppOrdensIdRouteImport.update({
  id: '/ordens/$id',
  path: '/ordens/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentosNovoRoute = AppOrcamentosNovoRouteImport.update({
  id: '/orcamentos/novo',
  path: '/orcamentos/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentosIdRoute = AppOrcamentosIdRouteImport.update({
  id: '/orcamentos/$id',
  path: '/orcamentos/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIdRoute = AppClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/site': typeof SiteRoute
  '/agenda': typeof AppAgendaRoute
  '/biblioteca': typeof AppBibliotecaRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/indicacoes': typeof AppIndicacoesRoute
  '/meu-site': typeof AppMeuSiteRoute
  '/modulos-futuros': typeof AppModulosFuturosRoute
  '/portal/$token': typeof PortalTokenRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/orcamentos/$id': typeof AppOrcamentosIdRoute
  '/orcamentos/novo': typeof AppOrcamentosNovoRoute
  '/ordens/$id': typeof AppOrdensIdRoute
  '/clientes/': typeof AppClientesIndexRoute
  '/orcamentos/': typeof AppOrcamentosIndexRoute
  '/ordens/': typeof AppOrdensIndexRoute
  '/portal/': typeof AppPortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/site': typeof SiteRoute
  '/agenda': typeof AppAgendaRoute
  '/biblioteca': typeof AppBibliotecaRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/indicacoes': typeof AppIndicacoesRoute
  '/meu-site': typeof AppMeuSiteRoute
  '/modulos-futuros': typeof AppModulosFuturosRoute
  '/portal/$token': typeof PortalTokenRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/orcamentos/$id': typeof AppOrcamentosIdRoute
  '/orcamentos/novo': typeof AppOrcamentosNovoRoute
  '/ordens/$id': typeof AppOrdensIdRoute
  '/clientes': typeof AppClientesIndexRoute
  '/orcamentos': typeof AppOrcamentosIndexRoute
  '/ordens': typeof AppOrdensIndexRoute
  '/portal': typeof AppPortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/site': typeof SiteRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/biblioteca': typeof AppBibliotecaRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/indicacoes': typeof AppIndicacoesRoute
  '/_app/meu-site': typeof AppMeuSiteRoute
  '/_app/modulos-futuros': typeof AppModulosFuturosRoute
  '/portal/$token': typeof PortalTokenRoute
  '/_app/clientes/$id': typeof AppClientesIdRoute
  '/_app/orcamentos/$id': typeof AppOrcamentosIdRoute
  '/_app/orcamentos/novo': typeof AppOrcamentosNovoRoute
  '/_app/ordens/$id': typeof AppOrdensIdRoute
  '/_app/clientes/': typeof AppClientesIndexRoute
  '/_app/orcamentos/': typeof AppOrcamentosIndexRoute
  '/_app/ordens/': typeof AppOrdensIndexRoute
  '/_app/portal/': typeof AppPortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/site'
    | '/agenda'
    | '/biblioteca'
    | '/configuracoes'
    | '/dashboard'
    | '/financeiro'
    | '/indicacoes'
    | '/meu-site'
    | '/modulos-futuros'
    | '/portal/$token'
    | '/clientes/$id'
    | '/orcamentos/$id'
    | '/orcamentos/novo'
    | '/ordens/$id'
    | '/clientes/'
    | '/orcamentos/'
    | '/ordens/'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/site'
    | '/agenda'
    | '/biblioteca'
    | '/configuracoes'
    | '/dashboard'
    | '/financeiro'
    | '/indicacoes'
    | '/meu-site'
    | '/modulos-futuros'
    | '/portal/$token'
    | '/clientes/$id'
    | '/orcamentos/$id'
    | '/orcamentos/novo'
    | '/ordens/$id'
    | '/clientes'
    | '/orcamentos'
    | '/ordens'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/site'
    | '/_app/agenda'
    | '/_app/biblioteca'
    | '/_app/configuracoes'
    | '/_app/dashboard'
    | '/_app/financeiro'
    | '/_app/indicacoes'
    | '/_app/meu-site'
    | '/_app/modulos-futuros'
    | '/portal/$token'
    | '/_app/clientes/$id'
    | '/_app/orcamentos/$id'
    | '/_app/orcamentos/novo'
    | '/_app/ordens/$id'
    | '/_app/clientes/'
    | '/_app/orcamentos/'
    | '/_app/ordens/'
    | '/_app/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SiteRoute: typeof SiteRoute
  PortalTokenRoute: typeof PortalTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/modulos-futuros': {
      id: '/_app/modulos-futuros'
      path: '/modulos-futuros'
      fullPath: '/modulos-futuros'
      preLoaderRoute: typeof AppModulosFuturosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meu-site': {
      id: '/_app/meu-site'
      path: '/meu-site'
      fullPath: '/meu-site'
      preLoaderRoute: typeof AppMeuSiteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/indicacoes': {
      id: '/_app/indicacoes'
      path: '/indicacoes'
      fullPath: '/indicacoes'
      preLoaderRoute: typeof AppIndicacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/biblioteca': {
      id: '/_app/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AppBibliotecaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal/': {
      id: '/_app/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof AppPortalIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ordens/': {
      id: '/_app/ordens/'
      path: '/ordens'
      fullPath: '/ordens/'
      preLoaderRoute: typeof AppOrdensIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orcamentos/': {
      id: '/_app/orcamentos/'
      path: '/orcamentos'
      fullPath: '/orcamentos/'
      preLoaderRoute: typeof AppOrcamentosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/': {
      id: '/_app/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AppClientesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ordens/$id': {
      id: '/_app/ordens/$id'
      path: '/ordens/$id'
      fullPath: '/ordens/$id'
      preLoaderRoute: typeof AppOrdensIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orcamentos/novo': {
      id: '/_app/orcamentos/novo'
      path: '/orcamentos/novo'
      fullPath: '/orcamentos/novo'
      preLoaderRoute: typeof AppOrcamentosNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orcamentos/$id': {
      id: '/_app/orcamentos/$id'
      path: '/orcamentos/$id'
      fullPath: '/orcamentos/$id'
      preLoaderRoute: typeof AppOrcamentosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/$id': {
      id: '/_app/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AppClientesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppBibliotecaRoute: typeof AppBibliotecaRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppIndicacoesRoute: typeof AppIndicacoesRoute
  AppMeuSiteRoute: typeof AppMeuSiteRoute
  AppModulosFuturosRoute: typeof AppModulosFuturosRoute
  AppClientesIdRoute: typeof AppClientesIdRoute
  AppOrcamentosIdRoute: typeof AppOrcamentosIdRoute
  AppOrcamentosNovoRoute: typeof AppOrcamentosNovoRoute
  AppOrdensIdRoute: typeof AppOrdensIdRoute
  AppClientesIndexRoute: typeof AppClientesIndexRoute
  AppOrcamentosIndexRoute: typeof AppOrcamentosIndexRoute
  AppOrdensIndexRoute: typeof AppOrdensIndexRoute
  AppPortalIndexRoute: typeof AppPortalIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppBibliotecaRoute: AppBibliotecaRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppIndicacoesRoute: AppIndicacoesRoute,
  AppMeuSiteRoute: AppMeuSiteRoute,
  AppModulosFuturosRoute: AppModulosFuturosRoute,
  AppClientesIdRoute: AppClientesIdRoute,
  AppOrcamentosIdRoute: AppOrcamentosIdRoute,
  AppOrcamentosNovoRoute: AppOrcamentosNovoRoute,
  AppOrdensIdRoute: AppOrdensIdRoute,
  AppClientesIndexRoute: AppClientesIndexRoute,
  AppOrcamentosIndexRoute: AppOrcamentosIndexRoute,
  AppOrdensIndexRoute: AppOrdensIndexRoute,
  AppPortalIndexRoute: AppPortalIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SiteRoute: SiteRoute,
  PortalTokenRoute: PortalTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
